# Generated by Django 4.2.23 on 2025-06-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('chat', 'Chat Mode'), ('quiz', 'Quiz Mode')], default='chat', max_length=10),
        ),
    ]
