# Generated by Django 4.2.23 on 2025-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('chat', 'Chat'), ('quiz', 'Quiz')], default='chat', max_length=10),
        ),
    ]
